# Generated by Django 4.0.3 on 2022-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0002_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='increased_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(verbose_name='Amount in grams'),
        ),
    ]
