# Generated by Django 4.0.3 on 2022-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0003_recipe_increased_price_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
