# Generated by Django 4.0.3 on 2022-04-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0004_alter_recipe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePriceIncrease',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_content.recipe')),
                ('increase_in_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('increased_price', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
