# Generated by Django 4.0.3 on 2022-04-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0005_recipepriceincrease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePriceIncrease',
        ),
    ]
