# Generated by Django 4.0.3 on 2022-04-07 21:59

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0006_delete_recipepriceincrease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[common.validators.letters_and_numbers_validator, django.core.validators.MinLengthValidator(2)], verbose_name='Ingredient name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_type',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=120, validators=[common.validators.letters_and_numbers_validator, django.core.validators.MinLengthValidator(2)], verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount in grams'),
        ),
    ]
