# Generated by Django 4.0.3 on 2022-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0007_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
