# Generated by Django 4.0.3 on 2022-04-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0009_alter_recipe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreasePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_content.recipe')),
            ],
        ),
    ]
