# Generated by Django 4.0.3 on 2022-04-08 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0011_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increasepercentage',
            name='percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
