# Generated by Django 4.0.3 on 2022-04-09 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0013_alter_ingredient_name_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increasepercentage',
            name='percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount in grams'),
        ),
    ]
