# Generated by Django 4.0.3 on 2022-04-14 07:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_content', '0017_alter_ingredient_name_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('user', 'name')},
        ),
    ]
