# Generated by Django 4.0.3 on 2022-04-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0019_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_recipe_name_unique'),
        ),
    ]
