# Generated by Django 4.0.3 on 2022-04-14 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0020_recipe_user_recipe_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_type',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price in leva'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='increased_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
