# Generated by Django 4.0.3 on 2022-04-26 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0021_alter_ingredient_price_per_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
