# Generated by Django 4.0.3 on 2022-04-05 11:20

import common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=72, null=True, validators=[django.core.validators.MinLengthValidator(2), common.validators.only_letters_validator])),
                ('last_name', models.CharField(blank=True, max_length=72, null=True, validators=[django.core.validators.MinLengthValidator(2), common.validators.only_letters_validator])),
                ('city_name', models.CharField(blank=True, max_length=72, null=True, validators=[common.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=100, null=True, validators=[common.validators.letters_and_numbers_validator, django.core.validators.MinLengthValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
