# Generated by Django 4.0.3 on 2022-04-14 07:18

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city_name',
            field=models.CharField(blank=True, max_length=72, null=True, validators=[common.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=72, null=True, validators=[django.core.validators.MinLengthValidator(2), common.validators.only_letters_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=72, null=True, validators=[django.core.validators.MinLengthValidator(2), common.validators.only_letters_validator], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[common.validators.LettersNumbersWhitespacesValidator('(?<![\\s\\W\\D])^([a-zA-Z0-9]+[\\s]?[a-zA-Z0-9]+)+$(?![\\s\\W\\D])'), django.core.validators.MinLengthValidator(1)], verbose_name="Restaurant's name"),
        ),
    ]
