# Generated by Django 4.0.3 on 2022-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('tea cup', 'tea cup'), ('coffee cup', 'coffee cup'), ('tablespoon', 'tablespoon'), ('teaspoon', 'teaspoon')], max_length=300)),
                ('amount_in_grams', models.IntegerField()),
                ('amount_in_milliliters', models.IntegerField()),
            ],
        ),
    ]
