# Generated by Django 4.0.3 on 2022-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunit',
            name='type',
            field=models.CharField(choices=[('teacup', 'teacup'), ('coffee cup', 'coffee cup'), ('tablespoon', 'tablespoon'), ('teaspoon', 'teaspoon')], max_length=300),
        ),
    ]
