# Generated by Django 4.0.3 on 2022-04-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0002_alter_measureunit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureunit',
            name='amount_in_grams',
        ),
        migrations.RemoveField(
            model_name='measureunit',
            name='product_name',
        ),
    ]
