# Generated by Django 4.0.3 on 2022-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0003_remove_measureunit_amount_in_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunit',
            name='type',
            field=models.CharField(max_length=300),
        ),
    ]
