# Generated by Django 4.0.3 on 2022-04-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0004_alter_measureunit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount_in_grams', models.IntegerField()),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_content.measureunit')),
            ],
        ),
    ]
