# Generated by Django 4.0.3 on 2022-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public_content', '0006_remove_product_measure_unit_delete_measureunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('tea_cup_in_grams', models.IntegerField()),
                ('coffee_cup_in_grams', models.IntegerField()),
                ('tablespoon_in_grams', models.IntegerField()),
                ('tea_spoon_in_grams', models.IntegerField()),
            ],
        ),
    ]
