# Generated by Django 4.0.3 on 2022-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coffee_cup_in_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tablespoon_in_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tea_cup_in_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tea_spoon_in_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
