# Generated by Django 4.0.3 on 2022-04-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0010_publicrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrecipe',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
