# Generated by Django 4.0.3 on 2022-04-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0011_publicrecipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicrecipe',
            name='ingredients',
        ),
    ]
