# Generated by Django 4.0.3 on 2022-04-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0013_publicrecipeingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicrecipeingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='PublicRecipe',
        ),
        migrations.DeleteModel(
            name='PublicRecipeIngredient',
        ),
    ]
